app/main/forms.py
# -*- coding:utf-8 -*-
__author__ = u'东方鹗'


from flask.ext.wtf import Form
from wtforms import StringField, SelectField, BooleanField, SubmitField


class SubscribeForm(Form):
	pass


class CollectForm(Form):
	pass


class SearchForm(Form):
	value = StringField()

app/main/__init__.py
# -*- coding:utf-8 -*-
__author__ = u'东方鹗'


from flask import Blueprint

main = Blueprint('main', __name__)
# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本main
from . import views, errors
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
# -*- coding:utf-8 -*-
__author__ = u'东方鹗'

from flask import render_template, request, redirect, url_for, flash, abort, g
from flask.ext.login import login_user, logout_user, login_required, current_user, current_app
from ..models import User, Album, Post
from .forms import SubscribeForm, CollectForm, SearchForm
from ..import db
from ..email import send_email
from .import main


@main.before_app_request
def before_request():
    search_form = SearchForm(prefix='search')
    page = request.args.get('page', 1, type=int)
    g.search_form = search_form
    if g.search_form.validate_on_submit() and g.search_form.value.data.strip() != '':
        from sqlalchemy import or_
        posts = Post.query.filter(or_(Post.body_html.like('%' + '%s' % g.search_form.value.data.strip() + '%'),
                                      Post.title.like('%' + '%s' % g.search_form.value.data.strip() + '%'),
                                      ),
                                  Post.confirmed==True, Post.disabled==False).order_by(Post.timestamp.desc())\
            .paginate(page, error_out=False)
        return render_template('main/search/posts.html', posts=posts)


@main.route('/', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    albums = Album.query.filter_by(confirmed=True, disabled=False).order_by(Album.timestamp.desc()).paginate(page, per_page=10, error_out=False)
    return render_template('main/index.html', albums=albums)

@main.route('/about')
def about():
    return render_template('main/about.html')



@main.route('/user/<username>')
def user(username):
    u = User.query.filter_by(username=username).first()
    if u is None:
        abort(404)
    my_albums = Album.query.filter_by(creator_id=u.id).all()
    my_posts = Post.query.filter_by(author_id=u.id).all()
    joined_albums = []
    for post in my_posts:
        if post.my_album.creator.id != u.id and post.my_album not in joined_albums:
            joined_albums.append(post.my_album)

    return render_template('main/user.html', user=u, my_albums=my_albums, joined_albums=joined_albums)


@main.route('/album/<int:album_id>', methods=['GET', 'POST'])
def album(album_id):
    a = Album.query.get_or_404(album_id)
    # if current_user != a.creator and not (current_user.is_administrator() or current_user.is_moderator()) and \
    #        (a.confirmed or not a.disabled):
    #    abort(403)
    subscribe_form = SubscribeForm(prefix='subscribe')
    if subscribe_form.validate_on_submit():
        if not current_user.is_authenticated():
            return redirect(request.args.get('next') or url_for('auth.login'))
        elif current_user.disabled:
            flash({'error': u'用户已被管理员注销！'})
            return redirect(request.args.get('next') or url_for('auth.login'))
        else:
            current_user.subscribe(album=a)
    post_confirmed_nums = Post.query.filter_by(album_id=a.id, confirmed=True, disabled=False).count()

    return render_template('main/album.html', album=a, subscribeForm=subscribe_form, post_confirmed_nums=post_confirmed_nums)


@main.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post(post_id):
    p = Post.query.get_or_404(post_id)
    collect_form = CollectForm(prefix='collect')
    if collect_form.validate_on_submit():
        if not current_user.is_authenticated():
            return redirect(request.args.get('next') or url_for('auth.login'))
        elif current_user.disabled:
            flash({'error': u'用户已被管理员注销！'})
            return redirect(request.args.get('next') or url_for('auth.login'))
        else:
            current_user.collect(post=p)

    posts = Post.query.filter_by(confirmed=True, disabled=False).all()
    pre_post = None
    next_post = None
    if p in posts:
        self_index = posts.index(p)
        if self_index - 1 >= 0:
            pre_post = posts[self_index - 1]
        if self_index + 1 < len(posts):
            next_post = posts[self_index + 1]
    return render_template('main/post.html', post=p, collectForm=collect_form, pre_post=pre_post, next_post=next_post)

app/templates/main/about.html
{% extends 'main/common/base.html' %}
{% block title %}
    {{ super() }}
    关于我们
{% endblock %}
{% block content %}
    <div class="container">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="page-header">
                        <h1>
                            尊敬的 {{ current_user.username }}
                        </h1>
                        <h3>
                            <code>欢迎使用藕丝空间获取知识！</code>
                        </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/album.html
{% extends 'main/common/base.html' %}
{% block title %}
    {{ super() }}
    {{ album.title }}
{% endblock %}
{% block content %}
    <form role="form" method="post" id="subscribe">
        {{ subscribeForm.hidden_tag() }}
        <h1 class="page-header text-center">
            {{ album.title }}
            <label class="pull-right" data-toggle="tooltip" data-placement="bottom" title="专辑拥有者将会抽取文章 <code>{{ album.percentage * 100 }}%</code> 的佣金。">
                {% if current_user.is_user() %}
                    <a class="btn btn-lg btn-primary disabled" style="margin-right: 10px" href="#"><i class="glyphicon glyphicon-pencil"> </i> 投稿</a>
                {% else %}
                    <a class="btn btn-lg btn-primary" style="margin-right: 10px" href="{{ url_for('auth.write_article', album_id=album.id) }}"><i class="glyphicon glyphicon-pencil"> </i> 投稿</a>
                {% endif %}
            </label>
            <div class="lead text-left">
                <br>
                <p style="text-indent: 2em">
                    {{ album.introduction }}
                </p>
                <br>
                <div class="small">
                    <a href="{{ url_for('main.user', username=album.creator.username) }}" title="作者"><span class="label label-success"><i class="glyphicon glyphicon-user"></i> {{ album.creator.username }}</span></a>
                    <span class="label label-primary" title="文章总数"><i class="glyphicon glyphicon-book"></i> {{ post_confirmed_nums }}</span>
                    <span class="label label-default" title="创建时间"><i class="glyphicon glyphicon-calendar"></i> {{ moment(album.timestamp).format('LL') }}</span>
                    {% if current_user.is_subscribing(album=album) or album.is_creator(current_user)%}
                        <a class="btn btn-xs btn-default disabled pull-right" href="javascript:void(0)"><i class="glyphicon glyphicon-bookmark"></i> 订阅</a>
                    {% else %}
                        <a class="btn btn-xs btn-primary pull-right" href="javascript:void(0)" onclick="$('#subscribe').submit()"><i class="glyphicon glyphicon-bookmark"></i> 订阅</a>
                    {% endif %}
                </div>
            </div>
        </h1>
    </form>
    {% for article in album.all_true_posts.items %}        
        <div class="panel text-left">
            <div class="panel-body">
                <div class="col-xs-12 col-md-3 col-lg-2">
                    <a href="{{ url_for('main.user', username=article.author.username) }}" title="{{ article.author.username }}">
                        <img class="img-circle" src="{{ article.author.gravatar(size=256) }}" style="height: 90px">
                    </a>
                </div>
                <div class="col-xs-12 col-md-8 col-lg-8">
                    <a href="{{ url_for('main.post', post_id=article.id) }}"> <h4>{{ article.title }}</h4>
                    <p style="text-indent: 2em">
                        {{ article.body_html|striptags|truncate(length=200, killwords=False, end="......") }}
                    </p></a>
                    <span class="label label-default" title="创建时间"><i class="glyphicon glyphicon-calendar"></i> {{ moment(article.timestamp).format('LL') }}</span>
                </div>
                 <div class="col-xs-12 col-md-1 col-lg-1">
                     <div class="col-lg-12" style="margin-top: 10px" title="收藏数"><span class="label label-warning"><i class="glyphicon glyphicon-star"></i> {{ article.my_collected }} </span></div>
                     <div class="col-lg-12" style="margin-top: 30px" title="价格"><span class="label label-danger"><i class="glyphicon glyphicon-thumbs-up"></i> {{ article.price|replace(0.0, '免费') }}</span></div>
                 </div>
            </div>
        </div>        
    {% endfor %}
    <!-- pagination 分页 -->
    <nav class="text-center">
        <ul class="pagination">
            <li {% if not album.all_true_posts.has_prev %}class="disabled"{% endif %}>
                <a href="{% if album.all_true_posts.has_prev %}{{ url_for('.album', album_id=album.id, page=album.all_true_posts.page - 1) }}{% else %}#{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for p in album.all_true_posts.iter_pages() %}
            {% if p %}
                {% if p == album.all_true_posts.page %}
                <li class="active"><a href="{{ url_for('.album', album_id=album.id, page=p) }}">{{ p }}</a></li>
                {% else %}
                <li><a href="{{ url_for('.album', album_id=album.id, page=p) }}">{{ p }}</a></li>
                {% endif %}
            {% else %}
            <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
            {% endfor %}
            <li {% if not album.all_true_posts.has_next %}class="disabled"{% endif %}>
                <a href="{% if album.all_true_posts.has_next %}{{ url_for('.album', album_id=album.id, page=album.all_true_posts.page + 1) }}{% else %}#{% endif %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    <!-- end pagination 分页 -->
{% endblock %}

app/templates/main/index.html
{% extends 'main/common/base.html' %}
{% block title %}
    {{ super() }}
    提升自我，创造未来！
{% endblock %}
{% block carousel %}
<!-- Carousel ================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>藕丝有<code>您</code>，更精彩！</h1>
                    <p style="margin-top: 90px"><a class="btn btn-lg btn-primary" href="{{ url_for('auth.register') }}" role="button">加入我们 ...</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>藕丝需要<code>您</code>！</h1>
                    <p style="margin-top: 90px"><a class="btn btn-lg btn-primary" href="{{ url_for('auth.register') }}" role="button">成为藕丝客 ...</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAFVVVQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1><code>您</code>需要藕丝空间！</h1>
                    <p style="margin-top: 90px"><a class="btn btn-lg btn-primary" href="{{ url_for('auth.register') }}" role="button">我要加入 ...</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->
{% endblock %}
{% block marketing %}
    {% for album in albums.items %}
        <!-- START THE FEATURETTES -->
        {% if loop.index % 2 != 0 %}
        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading"><a href="{{ url_for('main.album', album_id=album.id) }}">{{ album.title }}</a></h2>
                <p class="lead" style="text-indent: 2em">{{ album.introduction }}</p>
            </div>
            <div class="col-md-5">
                <a href="{{ url_for('main.album', album_id=album.id) }}">
                    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" src="{{ url_for('static', filename="uploads/album/%s" % album.picture_url) }}" alt="Generic placeholder image">
                </a>
            </div>
        </div>
        {% else %}
        <hr class="featurette-divider">
        <div class="row featurette">
            <div class="col-md-5">
                <a href="{{ url_for('main.album', album_id=album.id) }}">
                    <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" src="{{ url_for('static', filename="uploads/album/%s" % album.picture_url) }}" alt="Generic placeholder image">
                </a>
            </div>
            <div class="col-md-7">
                <h2 class="featurette-heading"><a href="{{ url_for('main.album', album_id=album.id) }}">{{ album.title }}</a></h2>
                <p class="lead" style="text-indent: 2em">{{ album.introduction }}</p>
            </div>
        </div>
        {% endif %}
    {% endfor %}
<!-- /END THE FEATURETTES -->
<!-- pagination 分页 -->
<nav class="text-center">
    <ul class="pagination pagination-lg">
        <li {% if not albums.has_prev %}class="disabled"{% endif %}>
            <a href="{% if albums.has_prev %}{{ url_for('.index', page=albums.page - 1) }}{% else %}#{% endif %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% for p in albums.iter_pages() %}
        {% if p %}
            {% if p == albums.page %}
            <li class="active"><a href="{{ url_for('.index', page=p) }}">{{ p }}</a></li>
            {% else %}
            <li><a href="{{ url_for('.index', page=p) }}">{{ p }}</a></li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
        {% endfor %}
        <li {% if not albums.has_next %}class="disabled"{% endif %}>
            <a href="{% if albums.has_next %}{{ url_for('.index', page=albums.page + 1) }}{% else %}#{% endif %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
<!-- end pagination 分页 -->
{% endblock %}

app/templates/main/post.html
{% extends 'main/common/base.html' %}
{% block title %}
    {{ super() }}
    {{ post.title }}
{% endblock %}
{% block content %}
    <form role="form" method="post" id="collect">
        {{ collectForm.hidden_tag() }}
        <h1 class="page-header">
            <a href="{{ url_for('main.album', album_id=post.album.id) }}" class="pull-left">
                <img class="img-circle" src="{{ url_for('static', filename="uploads/album/%s" % post.album.picture_url) }}" data-toggle="tooltip" data-placement="bottom" title="{{ post.album.title }}" style="height: 30px">
            </a>
            {{ post.title }}
            {% if current_user.is_collecting(post=post) or post.is_author(current_user) %}
                <a class="btn btn-xs btn-warning disabled pull-right" href="javascript:void(0)"><i class="glyphicon glyphicon-star"></i> 收藏</a>
            {% else %}
                <a class="btn btn-xs btn-primary pull-right" href="javascript:void(0)" onclick="$('#collect').submit()"><i class="glyphicon glyphicon-star-empty"></i> 收藏</a>
            {% endif %}
            <h6>
                <a href="{{ url_for('main.user', username=post.author.username) }}" title="作者"><span class="label label-success"><i class="glyphicon glyphicon-user"></i> {{ post.author.username }}</span></a>
                <span class="label label-danger" title="文章资费"><i class="glyphicon glyphicon-yen"></i> {{ post.price|replace(0.0, '免费') }}</span>
                <span class="label label-default" title="创建时间"><i class="glyphicon glyphicon-calendar"></i> {{ moment(post.timestamp).format('LL') }}</span>
            </h6>
        </h1>
    </form>
    <!--<div id="advertisement">
        <p>大家好，我是右侧浮动窗口，默认我是很正常的哦。鼠标下拉看看嘛，我会始终定位在浏览器这里的哦</p>
    </div>-->
    <div class="col-lg-offset-2 col-lg-8 text-left">
        <p>
            {{ post.body_html|safe }}
        </p>
        <nav class="col-lg-12">
            <ul class="pager">
                {% if pre_post %}
                    <li class="previous"><a href="{{ url_for('main.post', post_id=pre_post.id) }}" data-toggle="tooltip" data-placement="bottom" title="{{ pre_post.title }}"><span aria-hidden="true">&larr;</span> 上一篇</a></li>
                {% else %}
                    <li class="previous disabled"><a href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom" title="没有文章了"><span aria-hidden="true">&larr;</span> 上一篇</a></li>
                {% endif %}
                {% if next_post %}
                    <li class="next"><a href="{{ url_for('main.post', post_id=next_post.id) }}" data-toggle="tooltip" data-placement="bottom" title="{{ next_post.title }}">下一篇<span aria-hidden="true">&rarr;</span></a></li>
                {% else %}
                    <li class="next disabled"><a href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom" title="没有文章了">下一篇<span aria-hidden="true">&rarr;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}
{% block js %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/portamento-min.js') }}"></script>
    <script>
        $('#advertisement').portamento({disableWorkaround: true});
    </script>
{% endblock %}

app/templates/main/user.html
{% extends 'main/common/base.html' %}
{% block title %}
    {{ super() }}
    {{ user.username }}的资料
{% endblock %}
{% block content %}
    <div class="log-reg">
        {% if user.is_user() %}
            <img class="img-circle" src="{{ user.gravatar(size=256) }}" style="width: 90px; height: 90px">
            <h3>{{ user.username }}<span class="badge">一般用户</span></h3>
            <p class="small">注册时间：{{ moment(user.member_since).format('LLL') }}</p>
            <p class="small">最后登录时间：{{ moment(user.last_seen).fromNow(refresh=True) }}</p>
        {% elif user.is_real_user() %}
            <img class="img-circle" src="{{ user.gravatar(size=256) }}" style="width: 90px; height: 90px">
            <h3>{{ user.username }}<span class="badge">认证用户</span></h3>
            <p>真实姓名：<strong>{{ user.name|replace(None, '') }}</strong></p>
            <p class="small">注册时间：{{ moment(user.member_since).format('LLL') }}</p>
            <p class="small">最后登录时间：{{ moment(user.last_seen).fromNow(refresh=True) }}</p>
            <P>个人简介：{{ user.about_me|replace(None, '') }}</P>
            <p>文章数量：<code>{{ user.my_posts|length }}</code></p>
            <strong>参与的专辑</strong>
            {% for album in my_albums %}
                <p><a href="{{ url_for('main.album', album_id=album.id) }}">《{{ album.title }}》</a><span class="badge">原创</span></p>
            {% endfor %}
            {% for joined_album in joined_albums %}
                <p><a href="{{ url_for('main.album', album_id=joined_album.id) }}">《{{ joined_album.title }}》</a></p>
            {% endfor %}
        {% elif user.is_moderator() %}
            <img class="img-circle" src="{{ user.gravatar(size=256) }}" style="width: 90px; height: 90px">
            <h3>{{ user.username }}<span class="badge">协管员</span></h3>
            <p>真实姓名：<strong>{{ user.name|replace(None, '') }}</strong></p>
            个人简介：
            <P class="small">{{ user.about_me|replace(None, '') }}</P>
        {% elif user.is_administrator() %}
            <img class="img-circle" src="{{ user.gravatar(size=256) }}" style="width: 90px; height: 90px">
            <h3>{{ user.username }}<span class="badge">管理员</span></h3>
            <p>真实姓名：<strong>{{ user.name|replace(None, '') }}</strong></p>
            个人简介：
            <P class="small">{{ user.about_me|replace(None, '这家伙很懒，什么都没有留下......') }}</P>
        {% endif %}
    </div>
{% endblock %}