app/main/forms.py
# -*- coding:utf-8 -*-
__author__ = u'东方鹗'


from flask.ext.wtf import Form
from wtforms import StringField, SelectField, BooleanField, SubmitField


class SubscribeForm(Form):
	pass


class CollectForm(Form):
	pass


class SearchForm(Form):
	value = StringField()

app/main/__init__.py
# -*- coding:utf-8 -*-
__author__ = u'东方鹗'


from flask import Blueprint

main = Blueprint('main', __name__)
# 在末尾导入相关模块，是为了避免循环导入依赖，因为在下面的模块中还要导入蓝本main
from . import views, errors
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
# -*- coding:utf-8 -*-
__author__ = u'东方鹗'

from flask import render_template, request, redirect, url_for, flash, abort, g
from flask.ext.login import login_user, logout_user, login_required, current_user, current_app
from ..models import User, Album, Post
from .forms import SubscribeForm, CollectForm, SearchForm
from ..import db
from ..email import send_email
from .import main


@main.before_app_request
def before_request():
    search_form = SearchForm(prefix='search')
    page = request.args.get('page', 1, type=int)
    g.search_form = search_form
    if g.search_form.validate_on_submit() and g.search_form.value.data.strip() != '':
        from sqlalchemy import or_
        posts = Post.query.filter(or_(Post.body_html.like('%' + '%s' % g.search_form.value.data.strip() + '%'),
                                      Post.title.like('%' + '%s' % g.search_form.value.data.strip() + '%'),
                                      ),
                                  Post.confirmed==True, Post.disabled==False).order_by(Post.timestamp.desc())\
            .paginate(page, error_out=False)
        return render_template('main/search/posts.html', posts=posts)


@main.route('/', methods=['GET', 'POST'])
def index():
    page = request.args.get('page', 1, type=int)
    albums = Album.query.filter_by(confirmed=True, disabled=False).order_by(Album.timestamp.desc()).paginate(page, per_page=10, error_out=False)
    return render_template('main/index.html', albums=albums)

@main.route('/about')
def about():
    return render_template('main/about.html')



@main.route('/user/<username>')
def user(username):
    u = User.query.filter_by(username=username).first()
    if u is None:
        abort(404)
    my_albums = Album.query.filter_by(creator_id=u.id).all()
    my_posts = Post.query.filter_by(author_id=u.id).all()
    joined_albums = []
    for post in my_posts:
        if post.my_album.creator.id != u.id and post.my_album not in joined_albums:
            joined_albums.append(post.my_album)

    return render_template('main/user.html', user=u, my_albums=my_albums, joined_albums=joined_albums)


@main.route('/album/<int:album_id>', methods=['GET', 'POST'])
def album(album_id):
    a = Album.query.get_or_404(album_id)
    # if current_user != a.creator and not (current_user.is_administrator() or current_user.is_moderator()) and \
    #        (a.confirmed or not a.disabled):
    #    abort(403)
    subscribe_form = SubscribeForm(prefix='subscribe')
    if subscribe_form.validate_on_submit():
        if not current_user.is_authenticated():
            return redirect(request.args.get('next') or url_for('auth.login'))
        elif current_user.disabled:
            flash({'error': u'用户已被管理员注销！'})
            return redirect(request.args.get('next') or url_for('auth.login'))
        else:
            current_user.subscribe(album=a)
    post_confirmed_nums = Post.query.filter_by(album_id=a.id, confirmed=True, disabled=False).count()

    return render_template('main/album.html', album=a, subscribeForm=subscribe_form, post_confirmed_nums=post_confirmed_nums)


@main.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post(post_id):
    p = Post.query.get_or_404(post_id)
    collect_form = CollectForm(prefix='collect')
    if collect_form.validate_on_submit():
        if not current_user.is_authenticated():
            return redirect(request.args.get('next') or url_for('auth.login'))
        elif current_user.disabled:
            flash({'error': u'用户已被管理员注销！'})
            return redirect(request.args.get('next') or url_for('auth.login'))
        else:
            current_user.collect(post=p)

    posts = Post.query.filter_by(confirmed=True, disabled=False).all()
    pre_post = None
    next_post = None
    if p in posts:
        self_index = posts.index(p)
        if self_index - 1 >= 0:
            pre_post = posts[self_index - 1]
        if self_index + 1 < len(posts):
            next_post = posts[self_index + 1]
    return render_template('main/post.html', post=p, collectForm=collect_form, pre_post=pre_post, next_post=next_post)

app/templates/main/common/base.html
<!DOCTYPE html>
<html>
<head lang="zh">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="谦卑并倔强的活着！">
    <meta name="author" content="东方鹗">
    {% block favicon %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% endblock %}
    <title>{% block title %}藕丝空间——{% endblock %}</title>
    {% block css %}
        <!-- Bootstrap 核心 CSS -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">
        <!-- 自主样式 -->
        <link href="{{ url_for('static', filename='css/ousi-main.css') }}" rel="stylesheet">
    {% endblock %}
</head>
<body>
    {% include 'main/common/header.html' %}
    {% block carousel %}

    {% endblock %}
    <!-- Marketing messaging and featurettes  ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    <div class="container marketing">
        {% block marketing %}

        {% endblock %}
    </div>
    <div class="container content">
        {% block content %}

        {% endblock %}
    </div>
    {% include 'main/common/footer.html' %}
    {% block js %}
        <!-- Bootstrap 核心Javascript文件
        ===========================================================================  -->
        <!-- 将Javascript 文件放置于文件末尾，会提高网页加载速度。 -->
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.js')) }}
        {{ moment.lang('zh-cn') }}
        <script src="{{ url_for('static', filename='js/ousi-base.js') }}"></script>
    {% endblock %}
</body>
</html>

app/templates/main/common/footer.html
<!-- FOOTER -->
<hr class="featurette-divider">
<footer class="container">
    <p class="pull-right"><a href="#">回到顶部</a></p>
    <p>&copy; 2015 Company, Inc. &middot; <a href="{{ url_for('main.about') }}">关 于</a> <!--&middot; <a href="#">加入我们</a>-->&middot; <a href="http://www.miibeian.gov.cn" target="_blank"> 豫ICP备14004317</a></p>
</footer>

app/templates/main/common/header.html
<div class="navbar-wrapper">
    <div class="container">
        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    {% include 'common/brand.html' %}
                </div>
                    <div class="navbar-collapse collapse">
                    <!--<ul class="nav navbar-nav">
                        <li><a href="{{ url_for('main.index') }}">知 道</a></li>
                        <li><a href="#contact">工 具</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>-->
                    {% include 'common/logined.html' %}
                    {% include 'common/search.html' %}
                </div>
            </div>
        </div>

    </div>
</div>